CREATE TABLE IF NOT EXISTS Logs( id INT PRIMARY KEY AUTOINCREMENT, ip_address TEXT NOT NULL, timestamp TEXT NOT NULL, http_method TEXT, url_path TEXT, status_code INT);

CREATE TABLE IF NOT EXISTS Threat_Scores( id INT PRIMARY KEY AUTOINCREMENT, ip_address TEXT NOT NULL, anomaly_score REAL NOT NULL, evaluated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(ip_address) REFERENCES Logs(ip_address));

CREATE TABLE IF NOT EXISTS Flaggeg_IPs(id INTEGER PRIMARY KEY AUTOINCREMENT, ip_address TEXT UNIQUE NOT NULL, reason TEXT NOT NULL, flagged_on DATETIME DEFAULT CURRENT_TIMESTAMP);